services:
  couchbase:
    build:
      dockerfile: docker/Dockerfile
    container_name: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data: