global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pub-e2e'
    static_configs:
      - targets: ['host.docker.internal:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http

  # If you run multiple instances, add them here
  # - job_name: 'pub-producer'
  #   static_configs:
  #     - targets: ['host.docker.internal:9090']
  #   scrape_interval: 5s

  # - job_name: 'pub-consumer'
  #   static_configs:
  #     - targets: ['host.docker.internal:9091']
  #   scrape_interval: 5s